### ISSUE TITLE
Grammar detection is too loose

### ISSUE THREAD

**Issue by aendrew** [angular-ui/AngularJS-Atom#54]
Howdy!
First off, many thanks for the plugin, I find it really helpful when I'm building Angular apps. :+1: 

Secondly, alas, this week I'm working on a Polymer project, which is effectively nothing but HTML files. AngularJS-Atom's auto-detection is detecting all of my files as Angular, which is problematic for particularly style modules (wherein the entire file is just one style tag and some HTML imports), insomuch that they lose syntax highlighting altogether.

**Comment by aendrew** [comment]
Update: I've read a bit more about Atom grammars, and it seems that grammars are only detected by file extension and `firstLineMatch`. Doesn't help either that `language-html` uses [the doctype](https://github.com/atom/language-html/blob/master/grammars/html.cson#L12) for `firstLineMatch`, thus ensuring no template file or HTML import will ever benefit from its syntax highlighting... :-1: Any ideas?

**Comment by outsideris** [comment]
As you said, it is how auto detection works in Atom. I didn't use `firstLineMatch` because angular-template files don't include the doctype. 

You can change grammar at right-bottom of Atom editor without disabling AngularJS-Atom.

<img width="273" alt="2016-02-05 21 29 46" src="https://cloud.githubusercontent.com/assets/390146/12846392/b27b4e12-cc4f-11e5-944d-ad095f555162.png">

I don't have any idea to resolve the conflict between plain HTML files and angular's HTML files.

**Comment by aendrew** [comment]
Cool, figured as much. Bit of a shame Atom doesn't provide better routes for detecting grammars.

Closing for now, then. :smile:

**Comment by outsideris** [comment]
Good!!
